"""
Django settings for mrqc project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
from pathlib import Path
import time

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0,BASE_DIR)
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&psmntg+uax!^@4cdvatf*&r--c@o)!=jpoafbe3b(%@zvf&to'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.rcgl'

]

MIDDLEWARE = [
    'apps.rcgl.middlewares.TimeitMiddleware',#引入中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mrqc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mrqc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 指定simpleui默认的主题,指定一个文件名，相对路径就从simpleui的theme目录读取
SIMPLEUI_DEFAULT_THEME = 'layui.css'

#汽车logo
# SIMPLEUI_LOGO = 'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.zcool.cn%2Fcommunity%2F01ee07554399430000019ae9a56787.jpg%401280w_1l_2o_100sh.jpg&refer=http%3A%2F%2Fimg.zcool.cn&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1637159507&t=f9e0f2b3a39cc6d6f5814166a89e06b2'

SIMPLEUI_HOME_INFO = False

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['日常业务管理','汽配材料管理','客户管理','报表管理', '基础管理','预测分析管理'],      # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{  'name': 'Simpleui',
        'icon': 'fas fa-code',
        'url': 'https://gitee.com/tompeppa/simpleui'

    },
{
        'name': '日常业务管理' ,
        'icon': 'fa fa-bars',
        'models': [{
            'name': '预约登记',
            'url': '/rcgl/rcgl/',
            'icon': 'fas fa-shield-alt'
        }, {
            'name': '预约查询',
            'url': '/rcgl/rcgl/',
            'icon': 'fab fa-github'
        }, {
            'name': '美容方案制定',
            'url': 'rcgl/mrfan/',
            'icon': 'fab fa-github'
        }, {
            'name': '业务结算',
            'url': 'rcgl/mrfan/',
            'icon': 'fab fa-github'
        }],

    },{
        'name': '汽配材料管理' ,
        'icon': 'fa fa-desktop',
        'models': [{
            'name': '配料入库',
            'url': 'rcgl/liao/',
            'icon': 'far fa-surprise'
        },{
            'name': '领料入库',
            'url': 'rcgl/liao/',
            'icon': 'far fa-surprise'
        },{
            'name': '库存查询',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        },{
            'name': '供应商资料管理',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        }]
    },{
        'name': '客户管理' ,
        'icon': 'fa fa-desktop',
        'models': [{
            'name': '客户资料管理',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        },{
            'name': '客户车辆管理',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        }]
    },{
        'name': '报表管理' ,
        'icon': 'fa fa-desktop',
        'models': [{
            'name': '业务开单汇总',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        },{
            'name': '汽车出入库汇总',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        },{
            'name': '收入汇总',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        }]
    },{
        'name': '基础管理' ,
        'icon': 'fa fa-desktop',
        'models': [{
            'name': '人员管理',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'
        }, {
        'app': 'auth',
        'name': '权限管理',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': 'auth/user/'
        }]}]},{
            'name': '美容项目管理',
            'url': 'http://baidu.com',
            'icon': 'far fa-surprise'

},{
            'name': '预测分析管理' ,
            'icon': 'fa fa-desktop',
}

]}


autoescape = True
