# Generated by Django 3.2.8 on 2021-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcgl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=32, verbose_name='领料人')),
                ('pj_name', models.CharField(max_length=32, verbose_name='配件名称')),
                ('pj_uid', models.IntegerField(verbose_name='配件编号')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('jq', models.CharField(max_length=32, verbose_name='价钱')),
            ],
        ),
        migrations.AlterField(
            model_name='mrfan',
            name='status_info',
            field=models.IntegerField(choices=[(1, '审核'), (0, '未审核')], default=0, verbose_name='审核状态'),
        ),
    ]
